version: "3.8"
services:
  ipxe-iscsi:
    hostname: ipxeboot
    container_name: ipxeboot
    build: .
    ports: 
      - 69:69/udp
      - 880:80/tcp
      - 3260:3260/tcp
    volumes:
      - /volume1/docker/pxe/iso:/iso
    environment:
      - IPADDR=192.168.1.251
    restart: unless-stopped
